# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enable entities light source.
	entities = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wither_skeleton = true
				goat = true
				item_frame = true
				horse = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				tropical_fish = true
				fox = true
				pillager = true
				iron_golem = true
				cat = true
				zombie = true
				sheep = true
				player = true
				pufferfish = true
				trident = true
				villager = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				falling_block = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.supplementaries]
				falling_ash = true

			[light_sources.settings.entities.amendments]
				falling_lantern = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				birch_creeper = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				moobloom = true
				mauler = true
				crab = true
				rascal = true

			[light_sources.settings.entities.wilderwild]
				jellyfish = true
				crab = true
				firefly = true

			[light_sources.settings.entities.mobs_of_mythology]
				kobold_warrior = true
				chupacabra = true
				kobold = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true
